# CREATING THE DATABASE
CREATE DATABASE ONLINE_RETAIL;


# ACTIVATING THE DATABASE
USE ONLINE_RETAIL;


# CREATING THE RAW-DATA TABLE
CREATE TABLE RAW_DATA(
    INVOICE_NO VARCHAR(20),
    STOCK_CODE VARCHAR(20),
    DESCRIPTION TEXT,
    QUANTITY INT,
    INVOICE_DATE VARCHAR(50),
    UNIT_PRICE DECIMAL(10,2),
    CUSTOMER_ID INT,
    COUNTRY VARCHAR(50)
);


# IMPORTING THE RAW CSV FILE
LOAD DATA LOCAL INFILE 'C:/Users/sriva/OneDrive/Desktop/OnlineRetail.csv'
INTO TABLE RAW_DATA
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

SELECT COUNT(*) FROM RAW_DATA;


# DATA CONVERSION
UPDATE RAW_DATA
SET INVOICE_DATE = STR_TO_DATE(INVOICE_DATE, '%m/%d/%Y %H:%i');


# CREATING INDEXES
CREATE INDEX IDX_CUSTOMER_ID ON RAW_DATA(CUSTOMER_ID);
CREATE INDEX IDX_INVOICE_NO ON RAW_DATA(INVOICE_NO);
CREATE INDEX IDX_STOCK_CODE ON RAW_DATA(STOCK_CODE);
CREATE INDEX IDX_INVOICE_DATE ON RAW_DATA(INVOICE_DATE);


# CREATING FINAL TABLES

-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT PRIMARY KEY,
    COUNTRY VARCHAR(50),
    REGISTRATION_DATE DATETIME
);

-- PRODUCTS TABLE
CREATE TABLE PRODUCTS(
    PRODUCT_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255)
);

-- ORDERS TABLE
CREATE TABLE ORDERS(
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATETIME
);

-- ORDER ITEMS TABLE
CREATE TABLE ORDER_ITEMS(
    ORDER_ID VARCHAR(20),
    PRODUCT_ID VARCHAR(20),
    QUANTITY INT,
    UNIT_PRICE FLOAT
);


# INSERTING VALUES INTO THE TABLES

-- CUSTOMERS TABLE
CREATE TABLE TEMP_CUSTOMERS AS
SELECT 
    CUSTOMER_ID,
    MIN(COUNTRY) AS COUNTRY,
    MIN(INVOICE_DATE) AS "REGISTRATION DATE"
FROM RAW_DATA
GROUP BY CUSTOMER_ID;

INSERT INTO CUSTOMER
SELECT * FROM TEMP_CUSTOMER;

SELECT * FROM CUSTOMERS;

-- PRODUCT TABLE
INSERT INTO PRODUCTS
SELECT STOCK_CODE, 
       MIN(DESCRIPTION) AS "PRODUCT NAME"
FROM RAW_DATA
GROUP BY STOCK_CODE;

SELECT * FROM PRODUCTS;

-- ORDERS TABLE
INSERT INTO ORDERS
SELECT INVOICE_NO, 
       MIN(CUSTOMER_ID), 
       MIN(INVOICE_DATE)
FROM RAW_DATA
GROUP BY INVOICE_NO;

SELECT * FROM ORDERS;

-- ORDER ITEMS TABLE
INSERT INTO ORDER_ITEMS
SELECT INVOICE_NO, STOCK_CODE, QUANTITY, UNIT_PRICE
FROM RAW_DATA;

SELECT * FROM ORDER_ITEMS;


# ADDING INDEXATION TO FINAL TABLES
CREATE INDEX IDX_ORDERS_CUSTOMERS ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERITEMS_ORDERS ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDERITEMS_PRODUCTS ON ORDER_ITEMS(PRODUCT_ID);
CREATE INDEX IDX_ORDERS_DATE ON ORDERS(ORDER_DATE);


# KPI'S FOR DASHBOARDS

-- TOTAL REVENUE
SELECT SUM(QUANTITY * UNIT_PRICE) AS "TOTAL REVENUE"
FROM ORDER_ITEMS;

-- TOTAL ORDERS
SELECT COUNT(DISTINCT ORDER_ID) AS "TOTAL ORDERS"
FROM ORDERS;

-- AVERAGE ORDER VALUE
SELECT 
    SUM(QUANTITY * UNIT_PRICE) / COUNT(DISTINCT ORDER_ID) AS "AVERAGE ORDER VALUE"
FROM ORDER_ITEMS;


# CUSTOMER REVENUE
CREATE TEMPORARY TABLE CUSTOMER_REVENUE AS
SELECT 
    O.CUSTOMER_ID,
    SUM(OI.QUANTITY * OI.UNIT_PRICE) AS "REVENUE"
FROM ORDERS O
JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID;

SELECT * FROM CUSTOMER_REVENUE;


# RANKING BY REVENUE
SELECT RANK() OVER (ORDER BY REVENUE DESC) AS "RANK",
       CUSTOMER_ID,
       REVENUE
FROM CUSTOMER_REVENUE;


# RANKING BY NO. OF ORDERS
CREATE TEMPORARY TABLE CUSTOMER_ORDER_COUNTS AS
SELECT 
    CUSTOMER_ID,
    COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT * FROM CUSTOMER_ORDER_COUNTS;

-- RANKING QUERY
SELECT 
    RANK() OVER (ORDER BY TOTAL_ORDERS DESC) AS "RANK",
    TOTAL_ORDERS,
    CUSTOMER_ID    
FROM CUSTOMER_ORDER_COUNTS;


# MONTHLY REVENUE
CREATE TEMPORARY TABLE MONTHLY_REVENUE AS
SELECT 
    DATE_FORMAT(ORDER_DATE, '%Y-%m') AS MONTH,
    SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY MONTH
ORDER BY REVENUE DESC;

SELECT * FROM MONTHLY_REVENUE;


# COHORT ANALYSIS
CREATE TEMPORARY TABLE CUSTOMER_FIRST_ORDER AS
SELECT 
    CUSTOMER_ID,
    MIN(ORDER_DATE) AS FIRST_ORDER
FROM ORDERS
GROUP BY CUSTOMER_ID;

SELECT 
    DATE_FORMAT(C.FIRST_ORDER, '%Y-%m') AS COHORT,
    DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS ORDER_MONTH,
    COUNT(DISTINCT O.CUSTOMER_ID) AS USERS
FROM ORDERS O
JOIN CUSTOMER_FIRST_ORDER C 
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY COHORT, ORDER_MONTH;


# RFM METRICS
CREATE TEMPORARY TABLE RFM_BASE AS
SELECT 
    O.CUSTOMER_ID,
    MAX(O.ORDER_DATE) AS "LAST ORDER DATE",
    DATEDIFF(
        (SELECT MAX(ORDER_DATE) FROM ORDERS), 
        MAX(O.ORDER_DATE)
    ) AS RECENCY,
    COUNT(O.ORDER_ID) AS FREQUENCY,
    SUM(OI.QUANTITY * OI.UNIT_PRICE) AS MONETARY
FROM ORDERS O
JOIN ORDER_ITEMS OI 
    ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.CUSTOMER_ID;

SELECT * FROM RFM_BASE;

-- APPLY NTILE SCORING
CREATE TEMPORARY TABLE RFM_SCORES AS
SELECT *,
    NTILE(5) OVER (ORDER BY recency DESC) AS R_SCORE,
    NTILE(5) OVER (ORDER BY frequency ASC) AS F_SCORE,
    NTILE(5) OVER (ORDER BY monetary ASC) AS M_SCORE
FROM RFM_BASE;

SELECT * FROM RFM_SCORES;

-- COMBINE RFM SCORE
SELECT 
    CUSTOMER_ID,
    CONCAT(R_SCORE, F_SCORE, M_SCORE) AS RFM_SCORE
FROM RFM_SCORES;

-- CUSTOMER SEGMENTATION
SELECT 
    CUSTOMER_ID,
    CASE 
        WHEN R_SCORE >= 4 AND F_SCORE >= 4 AND M_SCORE >= 4 THEN 'Champions'
        WHEN R_SCORE >= 3 AND F_SCORE >= 3 THEN 'Loyal Customers'
        WHEN R_SCORE <= 2 AND F_SCORE >= 3 THEN 'At Risk'
        WHEN R_SCORE = 5 AND F_SCORE = 1 THEN 'New Customers'
        ELSE 'Others'
    END AS SEGMENT
FROM RFM_SCORES;


# CUSTOMER LIFETIME VALUE
SELECT 
    CUSTOMER_ID,
    SUM(OI.QUANTITY * OI.UNIT_PRICE) AS CLV
FROM ORDERS O
JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY CUSTOMER_ID
ORDER BY CLV DESC;


# REPEAT CUSTOMER RATE
SELECT 
    COUNT(DISTINCT CASE WHEN ORDER_COUNT > 1 THEN CUSTOMER_ID END) 
    / COUNT(DISTINCT CUSTOMER_ID) AS "REPEAT RATE"
FROM (
    SELECT CUSTOMER_ID, COUNT(*) AS ORDER_COUNT
    FROM ORDERS
    GROUP BY CUSTOMER_ID
) t;


# TOP PRODUCTS BY REVENUE
SELECT 
    PRODUCT_ID,
    SUM(QUANTITY * UNIT_PRICE) AS REVENUE
FROM ORDER_ITEMS
GROUP BY PRODUCT_ID
ORDER BY REVENUE DESC
LIMIT 10;


# REVENUE BY COUNTRIES
SELECT 
    C.COUNTRY,
    SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE
FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
GROUP BY C.COUNTRY
ORDER BY REVENUE DESC;


# AVERAGE FREQUENCY OF ORDERS
SELECT 
    AVG(order_count) AS "AVERAGE ORDERS PER CUSTOMER"
FROM (
    SELECT CUSTOMER_ID, COUNT(*) AS ORDER_COUNT
    FROM ORDERS
    GROUP BY CUSTOMER_ID
) t;


# TOP CUSTOMER PER COUNTRY
SELECT *
FROM (
    SELECT 
        C.COUNTRY,
        O.CUSTOMER_ID,
        SUM(OI.QUANTITY * OI.UNIT_PRICE) AS REVENUE,
        RANK() OVER (
            PARTITION BY C.COUNTRY 
            ORDER BY SUM(OI.QUANTITY * OI.UNIT_PRICE) DESC
        ) AS RNK
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
    GROUP BY C.COUNTRY, O.CUSTOMER_ID
) t
WHERE RNK = 1;